// 193 UN Member States
export const COUNTRIES_193 = [
  "Nigeria", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize",
  "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso",
  "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China",
  "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia",
  "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
  "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau",
  "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
  "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar",
  "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
  "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
  "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "North Korea", "North Macedonia", "Norway",
  "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
  "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
  "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan",
  "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
  "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
  "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

// All 36 Nigerian States + FCT with major cities & LGAs
export const NIGERIAN_STATES_AND_CITIES: Record<string, string[]> = {
  "Lagos": [
    "Ojo / Alaba", "Iba", "Festac / Amuwo Odofin", "Okokomaiko / Ijanikin", "Badagry",
    "Ikeja", "Victoria Island (VI)", "Lekki Phase 1", "Lekki / Ajah", "Ikoyi",
    "Surulere", "Yaba", "Gbagada", "Maryland", "Magodo", "Ojodu / Berger",
    "Agege", "Alimosho / Egbeda", "Ikorodu", "Epe", "Oshodi / Isolo", "Apapa"
  ],
  "Abuja (FCT)": ["Garki", "Wuse 1 & 2", "Maitama", "Asokoro", "Jabi", "Utako", "Gwarinpa", "Kubwa", "Lugbe", "Bwari", "Kuje"],
  "Abia": ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende"],
  "Adamawa": ["Yola", "Mubi", "Numan", "Jimeta", "Ganye"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak"],
  "Anambra": ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ihiala", "Ogbaru"],
  "Bauchi": ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum"],
  "Bayelsa": ["Yenagoa", "Brass", "Ogbia", "Sagbama", "Nembe"],
  "Benue": ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"],
  "Borno": ["Maiduguri", "Jere", "Biu", "Bama", "Monguno"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Obudu", "Akamkpa"],
  "Delta": ["Warri", "Asaba", "Sapele", "Ughelli", "Agbor", "Effurun"],
  "Ebonyi": ["Abakaliki", "Afikpo", "Onueke", "Ishielu", "Ezza"],
  "Edo": ["Benin City", "Auchi", "Ekpoma", "Uromi", "Igarra"],
  "Ekiti": ["Ado-Ekiti", "Ikere-Ekiti", "Ijero-Ekiti", "Oye-Ekiti", "Efon"],
  "Enugu": ["Enugu", "Nsukka", "Awgu", "Udi", "Oji River"],
  "Gombe": ["Gombe", "Kaltungo", "Bajoga", "Billiri", "Dukku"],
  "Imo": ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure", "Gumel", "Ringim"],
  "Kaduna": ["Kaduna", "Zaria", "Kafanchan", "Kagoro", "Saminaka"],
  "Kano": ["Kano Municipal", "Fagge", "Nassarawa", "Dala", "Tarauni", "Gwale", "Wudil"],
  "Katsina": ["Katsina", "Daura", "Funtua", "Malumfashi", "Kankia"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega"],
  "Kogi": ["Lokoja", "Okene", "Kabba", "Idah", "Ankpa"],
  "Kwara": ["Ilorin", "Offa", "Omu-Aran", "Lafiagi", "Jebba"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga", "Karu", "Nasarawa"],
  "Niger": ["Minna", "Suleja", "Bida", "Kontagora", "Lapai"],
  "Ogun": ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota / Sango", "Ilaro", "Ifo"],
  "Ondo": ["Akure", "Ondo City", "Owo", "Ikare", "Ore"],
  "Osun": ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Ikirun"],
  "Oyo": ["Ibadan", "Ogbomoso", "Oyo Town", "Iseyin", "Saki"],
  "Plateau": ["Jos", "Bukuru", "Pankshin", "Shendam", "Barkin Ladi"],
  "Rivers": ["Port Harcourt", "Obio-Akpor", "Bonny", "Eleme", "Oyigbo", "Ahoada"],
  "Sokoto": ["Sokoto", "Tambuwal", "Wamakko", "Gwadabawa", "Bodinga"],
  "Taraba": ["Jalingo", "Wukari", "Bali", "Takum", "Gembu"],
  "Yobe": ["Damaturu", "Potiskum", "Gashua", "Nguru", "Geidam"],
  "Zamfara": ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Maru"]
};
