import { Product } from "@/types";

export const INITIAL_PRODUCTS: Product[] = [
  // --- WOMEN'S EDIT ---
  {
    id: "plum-midi",
    name: "The Plum Midi Dress",
    department: "Women",
    category: "Dresses",
    price: 42000,
    sheet: "women.png",
    quadrant: 0,
    colors: ["#6b2948", "#211c23"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "A square neckline and an easy, close-to-body silhouette. A confident starting point for your evening edit.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "wide-denim",
    name: "The Wide-Leg Denim",
    department: "Women",
    category: "Denim",
    price: 46000,
    sheet: "women.png",
    quadrant: 1,
    colors: ["#6c8ca7", "#263c54"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "A wide-leg silhouette for your everyday rotation. Style it simply or make it the foundation of a layered look.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "cream-set",
    name: "The Off-Duty Matching Set",
    department: "Women",
    category: "Sets",
    price: 62000,
    sheet: "women.png",
    quadrant: 2,
    colors: ["#d4c3ae", "#835565"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "An easy coordinated look, with pieces you can wear together or make your own separately.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "plum-blouse",
    name: "The Plum Statement Blouse",
    department: "Women",
    category: "Tops",
    price: 34000,
    sheet: "women.png",
    quadrant: 3,
    colors: ["#602340", "#e3dcd1"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "A rich plum tone and an easy shape. Dress it up with tailored trousers or keep things relaxed.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "silk-halter-gown",
    name: "The Atelier Silk Halter Gown",
    department: "Women",
    category: "Dresses",
    price: 88000,
    sheet: "women.png",
    quadrant: 0,
    colors: ["#2d1b28", "#c8a27a"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Fluid mulberry silk blend with an elongated back tie. Crafted for galas, dinners, and special occasions.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "pleated-midi-skirt",
    name: "The Sculpted Pleated Midi Skirt",
    department: "Women",
    category: "Skirts",
    price: 38000,
    sheet: "women.png",
    quadrant: 1,
    colors: ["#1e2530", "#dfd8cd"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Sharp knife pleats that move effortlessly with every stride. High-waisted with a hidden side closure.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "cashmere-wrap-top",
    name: "The Ribbed Knit Wrap Top",
    department: "Women",
    category: "Tops",
    price: 36000,
    sheet: "women.png",
    quadrant: 2,
    colors: ["#b8a495", "#382933"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Ultra-soft ribbed knit with asymmetric crossover ties. Ideal for trans-seasonal layering.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "tailored-trench-coat",
    name: "The Double-Breasted Trench Coat",
    department: "Women",
    category: "Outerwear",
    price: 95000,
    sheet: "women.png",
    quadrant: 3,
    colors: ["#c5b59f", "#1c181b"],
    sizes: ["S", "M", "L", "XL"],
    description: "A timeless outerwear anchor. Water-resistant heavyweight gabardine with storm flaps and a belted waist.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "cargo-maxi-skirt",
    name: "The Technical Cargo Maxi Skirt",
    department: "Women",
    category: "Skirts",
    price: 44000,
    sheet: "women.png",
    quadrant: 1,
    colors: ["#3d3b36", "#a69b8d"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Streetwear utility meets architectural elegance. Features deep bellows pockets and back split vent.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "velvet-evening-wrap",
    name: "The Velvet Evening Corset Top",
    department: "Women",
    category: "Tops",
    price: 48000,
    sheet: "women.png",
    quadrant: 0,
    colors: ["#40152f", "#141416"],
    sizes: ["XS", "S", "M", "L"],
    description: "Internal boning with structured cups in deep royal velvet. Pair with tailored trousers or flowing skirts.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },

  // --- MEN'S EDIT ---
  {
    id: "core-tee",
    name: "The Everyday Oversized Tee",
    department: "Men",
    category: "Tops",
    price: 28000,
    sheet: "men.png",
    quadrant: 0,
    colors: ["#d9d2c5", "#292428"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A relaxed shape with dropped shoulders. Pair it with loose denim or your favourite everyday trousers.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "utility-jacket",
    name: "The Utility Jacket",
    department: "Men",
    category: "Jackets",
    price: 58000,
    sheet: "men.png",
    quadrant: 2,
    colors: ["#604c40", "#292428"],
    sizes: ["S", "M", "L", "XL"],
    description: "Clean lines and a relaxed fit bring an effortless finish to your outfit. Your next layer starts here.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "black-hoodie",
    name: "The After-Hours Hoodie",
    department: "Men",
    category: "Streetwear",
    price: 45000,
    sheet: "men.png",
    quadrant: 1,
    colors: ["#242125", "#87817e"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "A generous silhouette that belongs in your everyday wardrobe. Layer up with your favourite denim.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "relaxed-jeans",
    name: "The Relaxed Straight Jeans",
    department: "Men",
    category: "Denim",
    price: 48000,
    sheet: "men.png",
    quadrant: 3,
    colors: ["#6887a3", "#283845"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Everyday denim with room to move. A straight, relaxed cut for the outfits you come back to.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "wool-blazer",
    name: "The Structured Wool-Blend Blazer",
    department: "Men",
    category: "Tailoring",
    price: 92000,
    sheet: "men.png",
    quadrant: 2,
    colors: ["#1c1c1f", "#5c554e"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Modern single-breasted tailoring cut with relaxed shoulder pads. Transitions from boardroom to night out.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "cuban-collar-shirt",
    name: "The Minimalist Cuban Shirt",
    department: "Men",
    category: "Tops",
    price: 32000,
    sheet: "men.png",
    quadrant: 0,
    colors: ["#e8e2d8", "#2a363b"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Breathable textured cotton with open camp collar. Casual luxury designed for warm climates.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "heavyweight-cargo-pants",
    name: "The Heavyweight Cargo Trousers",
    department: "Men",
    category: "Streetwear",
    price: 52000,
    sheet: "men.png",
    quadrant: 3,
    colors: ["#3b362e", "#1b1a1c"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Structured cotton twill with articulated knees and adjustable cinch hems.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "suede-bomber",
    name: "The Faux-Suede Zip Bomber",
    department: "Men",
    category: "Jackets",
    price: 78000,
    sheet: "men.png",
    quadrant: 2,
    colors: ["#705446", "#231f20"],
    sizes: ["S", "M", "L", "XL"],
    description: "Plush brushed suede finish with gunmetal two-way zipper and ribbed knit cuffs.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "oxford-overshirt",
    name: "The Classic Oxford Overshirt",
    department: "Men",
    category: "Tops",
    price: 39000,
    sheet: "men.png",
    quadrant: 0,
    colors: ["#44627d", "#eae5dc"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "Garment-dyed heavyweight Oxford weave with dual chest patch pockets.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "boxy-graphic-tee",
    name: "The BGV Atelier Heavyweight Tee",
    department: "Men",
    category: "Streetwear",
    price: 29000,
    sheet: "men.png",
    quadrant: 1,
    colors: ["#141314", "#cfc9be"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: "300GSM organic cotton jersey with subtle tonal BGV embroidery on the chest.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },

  // --- UNISEX & ACCESSORIES ---
  {
    id: "monogram-leather-tote",
    name: "The Sculpted Leather Everyday Tote",
    department: "Unisex",
    category: "Accessories",
    price: 68000,
    sheet: "women.png",
    quadrant: 2,
    colors: ["#1c191a", "#784b38"],
    sizes: ["One Size"],
    description: "Full-grain supple leather tote bag with internal 16” laptop compartment and magnetic closure.",
    inStock: false,
    stockQuantity: 0,
    featured: true,
  },
  {
    id: "brushed-wool-scarf",
    name: "The Brushed Alpaca-Wool Scarf",
    department: "Unisex",
    category: "Accessories",
    price: 25000,
    sheet: "men.png",
    quadrant: 1,
    colors: ["#40152f", "#d5c8ba"],
    sizes: ["One Size"],
    description: "Oversized, ultra-warm brushed wool scarf finished with classic fringed edges.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "minimalist-crossbody",
    name: "The Technical Crossbody Bag",
    department: "Unisex",
    category: "Accessories",
    price: 32000,
    sheet: "men.png",
    quadrant: 3,
    colors: ["#1f1e21", "#4f584e"],
    sizes: ["One Size"],
    description: "Weather-resistant Cordura nylon with adjustable seatbelt webbing strap and matte black hardware.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
  {
    id: "signature-sunglasses",
    name: "The Geometric Acetate Sunglasses",
    department: "Unisex",
    category: "Accessories",
    price: 36000,
    sheet: "women.png",
    quadrant: 0,
    colors: ["#111111", "#593b2a"],
    sizes: ["One Size"],
    description: "Handcrafted Italian acetate frames with 100% UV400 protective polarized tinted lenses.",
    inStock: false,
    stockQuantity: 0,
    featured: false,
  },
];
