"use client";

import { useEffect, useState } from "react";
import { formatMoney } from "@/lib/money";

export default function AdminAnalyticsPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/admin/analytics").then((response) => response.json()).then((json) => { if (json.success) setData(json.data); }).finally(() => setLoading(false)); }, []);
  if (loading) return <div>Loading analytics...</div>;
  const metrics = [['Orders', data?.orders || 0], ['Verified revenue', formatMoney(data?.revenue || 0)], ['Products', data?.products || 0], ['Visitors today', data?.visitorsToday || 0], ['Active visitors', data?.activeVisitors || 0], ['Pending orders', data?.pendingOrders || 0], ['Completed orders', data?.completedOrders || 0], ['Payment failures', data?.paymentFailures || 0]];
  return <div style={{ maxWidth: 1280, margin: "0 auto" }}><h1 style={{ fontSize: "1.85rem", marginBottom: 6 }}>Analytics</h1><p style={{ color: "#6b7280", marginBottom: 24 }}>Live operational metrics from PostgreSQL, payment records, and anonymous visitor sessions.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 16, marginBottom: 24 }}>{metrics.map(([label, value]) => <div key={String(label)} style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, padding: 18 }}><div style={{ color: "#6b7280", fontSize: ".8rem", fontWeight: 700 }}>{label}</div><strong style={{ display: "block", fontSize: "1.55rem", marginTop: 6 }}>{value}</strong></div>)}</div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(360px,1fr))", gap: 20 }}><section style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, padding: 20 }}><h2 style={{ fontSize: "1.1rem", marginBottom: 14 }}>Top products</h2>{(data?.topProducts || []).map((product: any) => <div key={product.productName} style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: "1px solid #f3f4f6" }}><span>{product.productName}<small style={{ display: "block", color: "#6b7280" }}>{product.quantity} units</small></span><strong>{formatMoney(product.revenue)}</strong></div>)}{!data?.topProducts?.length && <p style={{ color: "#6b7280" }}>No order item data yet.</p>}</section><section style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, padding: 20 }}><h2 style={{ fontSize: "1.1rem", marginBottom: 14 }}>Recent activity</h2>{(data?.recentActivity || []).map((activity: any, index: number) => <div key={`${activity.type}-${index}`} style={{ display: "flex", justifyContent: "space-between", gap: 12, padding: "10px 0", borderBottom: "1px solid #f3f4f6" }}><span>{activity.label}<small style={{ display: "block", color: "#6b7280" }}>{new Date(activity.createdAt).toLocaleString()}</small></span><strong>{formatMoney(activity.amount)}</strong></div>)}{!data?.recentActivity?.length && <p style={{ color: "#6b7280" }}>No activity yet.</p>}</section></div></div>;
}
