"use client";

import { useEffect, useState } from "react";
import { formatMoney } from "@/lib/money";

export default function AdminPaymentsPage() {
  const [payments, setPayments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/admin/payments").then((response) => response.json()).then((json) => { if (json.success) setPayments(json.data.payments || []); }).finally(() => setLoading(false)); }, []);
  if (loading) return <div>Loading payment records...</div>;
  const successful = payments.filter((payment) => payment.status === "success");
  return <div style={{ maxWidth: 1280, margin: "0 auto" }}><h1 style={{ fontSize: "1.85rem", marginBottom: 6 }}>Payments</h1><p style={{ color: "#6b7280", marginBottom: 24 }}>Server-verified Paystack payment records.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 16, marginBottom: 24 }}><div style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, padding: 18 }}><span style={{ color: "#6b7280", fontSize: ".8rem", fontWeight: 700 }}>Successful</span><strong style={{ display: "block", fontSize: "1.7rem" }}>{successful.length}</strong></div><div style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, padding: 18 }}><span style={{ color: "#6b7280", fontSize: ".8rem", fontWeight: 700 }}>Verified revenue</span><strong style={{ display: "block", fontSize: "1.7rem" }}>{formatMoney(successful.reduce((sum, payment) => sum + payment.amount, 0))}</strong></div></div><div style={{ background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", fontSize: ".84rem" }}><thead><tr style={{ background: "#fafafa", textAlign: "left" }}>{['Reference','Order','Customer','Amount','Status','Channel','Created'].map((heading) => <th key={heading} style={{ padding: "12px 16px", borderBottom: "1px solid #e5e7eb" }}>{heading}</th>)}</tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} style={{ borderBottom: "1px solid #f3f4f6" }}><td style={{ padding: "12px 16px", fontFamily: "monospace" }}>{payment.reference}</td><td style={{ padding: "12px 16px" }}>{payment.order?.orderNumber || "Unknown"}</td><td style={{ padding: "12px 16px" }}>{payment.order?.customerName || "Unknown"}<div style={{ color: "#6b7280" }}>{payment.order?.customerEmail}</div></td><td style={{ padding: "12px 16px", fontWeight: 700 }}>{formatMoney(payment.amount, payment.currency)}</td><td style={{ padding: "12px 16px", color: payment.status === "success" ? "#047857" : "#b45309", fontWeight: 700 }}>{payment.status}</td><td style={{ padding: "12px 16px" }}>{payment.channel || "-"}</td><td style={{ padding: "12px 16px" }}>{new Date(payment.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{payments.length === 0 && <p style={{ padding: 24, color: "#6b7280" }}>No payment records yet.</p>}</div></div>;
}
